//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EstiloMestre.Exceptions.ExceptionsBase {
    using System;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ResourceMessagesExceptions {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ResourceMessagesExceptions() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("EstiloMestre.Exceptions.ExceptionsBase.ResourceMessagesExceptions", typeof(ResourceMessagesExceptions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string NAME_EMPTY {
            get {
                return ResourceManager.GetString("NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string EMAIL_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_INVALID", resourceCulture);
            }
        }
        
        public static string EMAIL_EMPTY {
            get {
                return ResourceManager.GetString("EMAIL_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_EMPTY {
            get {
                return ResourceManager.GetString("PASSWORD_EMPTY", resourceCulture);
            }
        }
        
        public static string PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("PASSWORD_INVALID", resourceCulture);
            }
        }
        
        public static string UNKNOW_EXCEPTION {
            get {
                return ResourceManager.GetString("UNKNOW_EXCEPTION", resourceCulture);
            }
        }
        
        public static string EMAIL_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("EMAIL_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string EMAIL_OR_PASSWORD_INVALID {
            get {
                return ResourceManager.GetString("EMAIL_OR_PASSWORD_INVALID", resourceCulture);
            }
        }
        
        public static string NO_TOKEN {
            get {
                return ResourceManager.GetString("NO_TOKEN", resourceCulture);
            }
        }
        
        public static string USER_WITHOUT_PERMISSION_ACCESS_RESOURCE {
            get {
                return ResourceManager.GetString("USER_WITHOUT_PERMISSION_ACCESS_RESOURCE", resourceCulture);
            }
        }
        
        public static string BARBERSHOP_NAME_EMPTY {
            get {
                return ResourceManager.GetString("BARBERSHOP_NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string ADDRESS_EMPTY {
            get {
                return ResourceManager.GetString("ADDRESS_EMPTY", resourceCulture);
            }
        }
        
        public static string TOKEN_EXPIRED {
            get {
                return ResourceManager.GetString("TOKEN_EXPIRED", resourceCulture);
            }
        }
        
        public static string BARBERSHOP_ID_NOT_FOUND_IN_ROUTE {
            get {
                return ResourceManager.GetString("BARBERSHOP_ID_NOT_FOUND_IN_ROUTE", resourceCulture);
            }
        }
        
        public static string BARBERSHOP_ID_INVALID_IN_ROUTE {
            get {
                return ResourceManager.GetString("BARBERSHOP_ID_INVALID_IN_ROUTE", resourceCulture);
            }
        }
        
        public static string USER_NOT_FOUND {
            get {
                return ResourceManager.GetString("USER_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string EMPLOYEE_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("EMPLOYEE_ALREADY_REGISTERED", resourceCulture);
            }
        }
        
        public static string SERVICE_NAME_EMPTY {
            get {
                return ResourceManager.GetString("SERVICE_NAME_EMPTY", resourceCulture);
            }
        }
        
        public static string SERVICE_NAME_TOO_LONG {
            get {
                return ResourceManager.GetString("SERVICE_NAME_TOO_LONG", resourceCulture);
            }
        }
        
        public static string SERVICE_DESCRIPTION_TOO_LONG {
            get {
                return ResourceManager.GetString("SERVICE_DESCRIPTION_TOO_LONG", resourceCulture);
            }
        }
        
        public static string SERVICE_ALREADY_EXISTS {
            get {
                return ResourceManager.GetString("SERVICE_ALREADY_EXISTS", resourceCulture);
            }
        }
        
        public static string AT_LEAST_ONE_SERVICE_REQUIRED {
            get {
                return ResourceManager.GetString("AT_LEAST_ONE_SERVICE_REQUIRED", resourceCulture);
            }
        }
        
        public static string SERVICE_ID_INVALID {
            get {
                return ResourceManager.GetString("SERVICE_ID_INVALID", resourceCulture);
            }
        }
        
        public static string SERVICE_PRICE_INVALID {
            get {
                return ResourceManager.GetString("SERVICE_PRICE_INVALID", resourceCulture);
            }
        }
        
        public static string SERVICE_DURATION_INVALID {
            get {
                return ResourceManager.GetString("SERVICE_DURATION_INVALID", resourceCulture);
            }
        }
        
        public static string SERVICE_WITH_ID_NOT_FOUND {
            get {
                return ResourceManager.GetString("SERVICE_WITH_ID_NOT_FOUND", resourceCulture);
            }
        }
        
        public static string SERVICE_WITH_ID_ALREADY_REGISTERED {
            get {
                return ResourceManager.GetString("SERVICE_WITH_ID_ALREADY_REGISTERED", resourceCulture);
            }
        }
    }
}
